menu:
  - name: Posts
    url: /posts/
  - name: Categories
    url: /categories/
  - name: Tags
    url: /tags/
  - name: Archives
    url: /archives/
  - name: About
    url: /about/

# socialLink:
#   - name: Github
#     link: https://github.com/ammikeya
#   - name: Facebook
#     link: https://github.com/hai-zou/hexo-theme-sea
#   - name: Telegram
#     link: https://github.com/hai-zou/hexo-theme-sea
#   - name: Instagram
#     link: https://github.com/hai-zou/hexo-theme-sea

# favicon: /logo.svg

search:
  enable: false
  type: algolia